apps/member/urls.py
#!/usr/bin/env python

# -*- mode: python; coding: utf-8 -*-
# Copyright (C) 2018-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'member'
urlpatterns = [
    path('signup/',views.UserCreateView.as_view(),name="signup"),
    path('club/',views.ClubListView.as_view(),name="club_list"),
    path('club/<int:pk>/',views.ClubDetailView.as_view(),name="club_detail"),
    path('club/<int:pk>/add_member/',views.ClubAddMemberView.as_view(),name="club_add_member"),
    path('club/create/',views.ClubCreateView.as_view(),name="club_create"),
    path('user/',views.UserListView.as_view(),name="user_list"),
    path('user/<int:pk>',views.UserDetailView.as_view(),name="user_detail")
]

apps/note/urls.py
# -*- mode: python; coding: utf-8 -*-
# Copyright (C) 2018-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views

app_name = 'note'
urlpatterns = [
    path('transfer/', views.TransactionCreate.as_view(), name='transfer'),
    path('buttons/create/',views.TransactionTemplateCreateView.as_view(),name='template_create'),
    path('buttons/update/<int:pk>/',views.TransactionTemplateUpdateView.as_view(),name='template_update'),
    path('buttons/',views.TransactionTemplateListView.as_view(),name='template_list')
]

note_kfet/urls.py
# -*- mode: python; coding: utf-8 -*-
# Copyright (C) 2018-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    # Dev so redirect to something random
    path('', RedirectView.as_view(pattern_name='note:transfer'), name='index'),

    # Include project routers
    path('note/', include('note.urls')),

    # Include Django Contrib and Core routers
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('member.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

apps/member/models.py
# -*- mode: python; coding: utf-8 -*-
# Copyright (C) 2018-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from django.urls import reverse, reverse_lazy

class Profile(models.Model):
    """
    An user profile

    We do not want to patch the Django Contrib Auth User class
    so this model add an user profile with additional information.
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    phone_number = models.CharField(
        verbose_name=_('phone number'),
        max_length=50,
        blank=True,
        null=True,
    )
    section = models.CharField(
        verbose_name=_('section'),
        help_text=_('e.g. "1A0", "9A♥", "SAPHIRE"'),
        max_length=255,
        blank=True,
        null=True,
    )
    address = models.CharField(
        verbose_name=_('address'),
        max_length=255,
        blank=True,
        null=True,
    )
    paid = models.BooleanField(
        verbose_name=_("paid"),
        default=False,
    )

    class Meta:
        verbose_name = _('user profile')
        verbose_name_plural = _('user profile')

    def get_absolute_url(self):
        return reverse('user_detail',args=(self.pk,))

class Club(models.Model):
    """
    A student club
    """
    name = models.CharField(
        verbose_name=_('name'),
        max_length=255,
        unique=True,
    )
    email = models.EmailField(
        verbose_name=_('email'),
    )

    # Memberships
    membership_fee = models.PositiveIntegerField(
        verbose_name=_('membership fee'),
    )
    membership_duration = models.DurationField(
        null=True,
        verbose_name=_('membership duration'),
        help_text=_('The longest time a membership can last '
                    '(NULL = infinite).'),
    )
    membership_start = models.DurationField(
        null=True,
        verbose_name=_('membership start'),
        help_text=_('How long after January 1st the members can renew '
                    'their membership.'),
    )
    membership_end = models.DurationField(
        null=True,
        verbose_name=_('membership end'),
        help_text=_('How long the membership can last after January 1st '
                    'of the next year after members can renew their '
                    'membership.'),
    )

    class Meta:
        verbose_name = _("club")
        verbose_name_plural = _("clubs")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('member:club_detail', args=(self.pk,))


class Role(models.Model):
    """
    Role that an user can have in a club
    """
    name = models.CharField(
        verbose_name=_('name'),
        max_length=255,
        unique=True,
    )

    class Meta:
        verbose_name = _('role')
        verbose_name_plural = _('roles')


class Membership(models.Model):
    """
    Register the membership of a user to a club, including roles and membership duration.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT
    )
    club = models.ForeignKey(
        Club,
        on_delete=models.PROTECT
    )
    roles = models.ForeignKey(
        Role,
        on_delete=models.PROTECT
    )
    date_start = models.DateField(
        verbose_name=_('membership starts on'),
    )
    date_end = models.DateField(
        verbose_name=_('membership ends on'),
        null=True,
    )
    fee = models.PositiveIntegerField(
        verbose_name=_('fee'),
    )

    class Meta:
        verbose_name = _('membership')
        verbose_name_plural = _('memberships')


# @receiver(post_save, sender=settings.AUTH_USER_MODEL)
# def save_user_profile(instance, created, **_kwargs):
#     """
#     Hook to save an user profile when an user is updated
#     """
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()

apps/member/forms.py
# -*- mode: python; coding: utf-8 -*-
# Copyright (C) 2018-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Profile, Club, Membership

from django.utils.translation import gettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms import layout, bootstrap
from crispy_forms.bootstrap import InlineField, FormActions, StrictButton, Div, Field
from crispy_forms.layout import Layout


class ProfileForm(forms.ModelForm):
    """
    Forms pour la création d'un profile utilisateur.
    """
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields ='__all__'

class AddMembersForm(forms.Form):
    class Meta:
        fields = ('',)

class MembershipForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ('user','roles','date_start')

MemberFormSet = forms.modelformset_factory(Membership,
                                           form=MembershipForm,
                                           extra=2,
                                           can_delete=True)

class FormSetHelper(FormHelper):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.form_tag = False
        self.form_method = 'POST'
        self.form_class='form-inline'
        # self.template = 'bootstrap/table_inline_formset.html'
        self.layout = Layout(
            Div(
                Div('user',css_class='col-sm-2'),
                Div('roles',css_class='col-sm-2'),
                Div('date_start',css_class='col-sm-2'),
                css_class="row formset-row",
            )
        )

apps/member/views.py
#!/usr/bin/env python

# Copyright (C) 2018-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, ListView, DetailView
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.db.models import Q

from django_tables2.views import SingleTableView


from .models import Profile, Club, Membership
from .forms import ProfileForm, ClubForm,MembershipForm, MemberFormSet,FormSetHelper
from .tables import ClubTable,UserTable
from .filters import UserFilter, UserFilterFormHelper


from note.models.transactions import Transaction
from note.tables import HistoryTable

class UserCreateView(CreateView):
    """
    Une vue pour inscrire un utilisateur et lui créer un profile
    """

    form_class = ProfileForm
    success_url = reverse_lazy('login')
    template_name ='member/signup.html'
    second_form = UserCreationForm

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["user_form"] = self.second_form

        return context

    def form_valid(self, form):
        user_form = UserCreationForm(self.request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user_profile = form.save(commit=False) # do not save to db
            user_profile.user = user
            user_profile.save()
        return super().form_valid(form)

class UserDetailView(LoginRequiredMixin,DetailView):
    """
    Affiche les informations sur un utilisateur, sa note, ses clubs ...
    """
    model = Profile
    context_object_name = "profile"
    def get_context_data(slef,**kwargs):
        context = super().get_context_data(**kwargs)
        user = context['profile'].user
        history_list = \
            Transaction.objects.all().filter(Q(source=user.note) | Q(destination=user.note))
        context['history_list'] = HistoryTable(history_list)
        club_list = \
            Membership.objects.all().filter(user=user).only("club")
        context['club_list'] = ClubTable(club_list)
        return context

class UserListView(LoginRequiredMixin,SingleTableView):
    """
    Affiche la liste des utilisateurs, avec une fonction de recherche statique
    """
    model = User
    table_class = UserTable
    template_name = 'member/user_list.html'
    filter_class = UserFilter
    formhelper_class = UserFilterFormHelper

    def get_queryset(self,**kwargs):
        qs = super().get_queryset()
        self.filter = self.filter_class(self.request.GET,queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filter
        return context


###################################
############## CLUB ###############
###################################

class ClubCreateView(LoginRequiredMixin,CreateView):
    """
    Create Club
    """
    model = Club
    form_class = ClubForm

    def form_valid(self,form):
        return super().form_valid(form)

class ClubListView(LoginRequiredMixin,SingleTableView):
    """
    List existing Clubs
    """
    model = Club
    table_class = ClubTable

class ClubDetailView(LoginRequiredMixin,DetailView):
    model = Club
    context_object_name="club"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        club = context["club"]
        club_transactions =  \
            Transaction.objects.all().filter(Q(source=club.note) | Q(destination=club.note))
        context['history_list'] = HistoryTable(club_transactions)
        club_member = \
            Membership.objects.all().filter(club=club)
        # TODO: consider only valid Membership
        context['member_list'] = club_member
        return context

class ClubAddMemberView(LoginRequiredMixin,CreateView):
    model = Membership
    form_class = MembershipForm
    template_name = 'member/add_members.html'
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = MemberFormSet()
        context['helper'] = FormSetHelper()
        return context

    def post(self,request,*args,**kwargs):
        formset = MembershipFormset(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            return self.form_invalid(formset)

    def form_valid(self,formset):
        formset.save()
        return super().form_valid(formset)

templates/member/add_members.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<form method="post" action="">
    {% csrf_token %}
    {% crispy formset helper %}
    <div class="form-actions">
        <input type="submit" name="submit" value="Add Members" class="btn btn-primary" id="submit-save">
    </div>
</form>

<!-- Include formset plugin - including jQuery dependency -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'js/dynamic-formset.js' %}"></script>
<script>
    $('.formset-row').formset({
        addText: 'add another',          // Text for the add link
        deleteText: 'remove',            // Text for the delete link
        addCssClass: 'btn btn-primary',          // CSS class applied to the add link
        deleteCssClass: 'btn btn-danger h-50 my-auto',
    });
</script>
{% endblock %}

templates/member/club_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load render_table from django_tables2 %}
{% load pretty_money %}
{% block content %}
<p><a class="btn btn-primary" href="{% url 'member:club_list' %}">Clubs</a></p>
<h3 class="text-center"> Club {{ object.name }}</h3>
<dl>
    <dt>{% trans 'Membership starts on' %}</dt>
    <dd>{{ club.membership_start }}</dd>
    <dt>{% trans 'Membership ends on' %}</dt>
    <dd>{{ club.membership_end }}</dd>
    <dt>{% trans 'Membership duration' %}</dt>
    <dd>{{ club.membership_duration }}</dd>
    <dt> Aliases </dt>
    <dd>{{ club.note.aliases_set.all }}</dd>
    <dt>{% trans 'balance' %}</dt>
    <dd>{{ club.note.balance | pretty_money }}</dd>

</dl>


<div class="btn-group" role="group">
    <a class="btn btn-primary" href="{% url 'member:club_add_member' pk=object.pk %}"> Ajouter des membres </a>
    <a class="btn btn-primary" href="{% url 'member:club_add_member' pk=object.pk %}"> Modifier les informations </a>
    <a class="btn btn-primary" href="{% url 'member:club_add_member' pk=object.pk %}"> Ajouter des roles </a>
</div>

<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <i class="fa fa-users"></i> Membres du club
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">

          {% render_table member_list %}
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            <i class="fa fa-euro"></i> Historique des transactions
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
          {% render_table history_list %}
      </div>
    </div>
  </div>
</div>
    {% endblock %}

templates/member/club_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'note:template_list' %}">Template Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/member/club_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% block content %}

{% render_table  table %}

<a class="btn btn-primary" href="{% url 'member:club_create' %}">New Club</a>

{% endblock %}
{% block extrajavascript %}
<script type="text/javascript">

$(document).ready(function($) {
    $(".table-row").click(function() {
        window.document.location = $(this).data("href");
    });
});

</script>
{% endblock %}

templates/member/profile_detail.html
{% extends "base.html" %}
{% load i18n static pretty_money django_tables2 %}

{% block content %}
    <h3>Compte n° {{ object.pk }}</h3>

    <img src="{{ object.note.display_image.url }}" alt=""/>

    <dl class="row">
        <dt class="col-6 col-md-3">{% trans 'name'|capfirst %}</dt>
        <dd class="col-6 col-md-3">{{ object.user.name }}</dd>
        <dt class="col-6 col-md-3">{% trans 'first name'|capfirst %}</dt>
        <dd class="col-6 col-md-3">{{ object.user.first_name }}</dd>
        <dt class="col-6 col-md-3">{% trans 'username'|capfirst %}</dt>
        <dd class="col-6 col-md-3">{{ object.user.username }}</dd>
        <dt class="col-6 col-md-3">Aliases</dt>
        <dd class="col-6 col-md-3">{{ object.user.note.aliases_set.all }}</dd>
        <dt class="col-6 col-md-3">{% trans 'section'|capfirst %}</dt>
        <dd class="col-6 col-md-3">{{ object.section }}</dd>
        <dt class="col-6 col-md-3">{% trans 'address'|capfirst %}</dt>
        <dd class="col-6 col-md-3">{{ object.address }}</dd>
        <dt class="col-6 col-md-3">{% trans 'balance'|capfirst %}</dt>
        <dd class="col-6 col-md-3">{{ object.user.note.balance | pretty_money }}</dd>
    </dl>

    <a class="btn btn-primary" href="{% url 'password_change' %}">{% trans 'Change password' %}</a>

<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <i class="fa fa-users"></i> {% trans "View my memberships" %}
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        {% render_table club_list %}
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            <i class="fa fa-euro"></i> Historique des transactions
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
          {% render_table history_list %}
      </div>
    </div>
  </div>
</div>




    {% endblock %}

templates/member/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ user_form|crispy }}
    {{ form|crispy }}
      <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/member/user_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags%}
{% block content %}

<a class="btn btn-primary" href="{% url 'member:signup' %}">New User</a>

<div class="row">
{% crispy filter.form filter.form.helper %}
</div>
<div class="row">
    <div id="replaceable-content" class="col-6">
        {% render_table  table %}
    </div>
</div>

{% endblock %}

{% block extrajavascript %}
<script type="text/javascript">

$(document).ready(function($) {
    $(".table-row").click(function() {
        window.document.location = $(this).data("href");
    });
});

</script>
{% endblock %}